# Generated by Django 3.1.7 on 2021-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=10)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=3)),
                ('billable', models.BooleanField(default=False)),
                ('billable_rate', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Timesheet',
                'verbose_name_plural': 'Timesheets',
                'ordering': ('created', 'billable'),
            },
        ),
    ]
