# Generated by Django 3.1.7 on 2021-03-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210323_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='billable_rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
