# Generated by Django 3.1.7 on 2021-09-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210323_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='billable_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
